---
- name: create bin dir
  file:
    path: '{{item.dest}}'
    mode: 0744
    state: directory
  with_items: '{{MKL_DEPENDENCIES}}'

- name: create tmp dir
  file:
    path: '{{item.tmp}}'
    mode: 0744
    state: directory
  with_items: '{{MKL_DEPENDENCIES}}'

- name: download mkl dependencies
  get_url:
    url: "{{item.src}}"
    dest: "{{item.tmp}}/{{item.name}}" 
    mode: 0644
  with_items: '{{MKL_DEPENDENCIES}}'


- name: copy mkl dependencies
  unarchive:
    src: '{{item.tmp}}/{{item.name}}'
    dest: '{{item.dest}}'
    copy: no
  with_items: '{{MKL_DEPENDENCIES}}'
