---
- name: create bin dir
  file:
    path: '{{item.dest}}'
    mode: 0744
    state: directory
  with_items: '{{MKL_DEPENDENCIES}}'
  
 
#- name: debug
#  debub: msg="{{MKL_DEPENDENCIES}}"
  
- name: copy mkl dependencies
  unarchive:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    copy: no
    list_files: yes
  with_items: '{{MKL_DEPENDENCIES}}'